version: 2
jobs:
  build:
    working_directory: ~/phone-book-graphql
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-phone-book-graphql
          command: npm install
      - run:
          name: lint-code
          command: npm run code:check       
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules