version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-code-check:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run code:check
workflows:
    build-and-code-check:
      jobs:
        - build-and-code-check